artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: none
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  option: google
  fileid: 1xLxEJn7s5waivRbKG7zaw66Sn8FjeWLe

